In [270]:
import numpy as np
from sklearn.cross_validation import KFold
from pandas import DataFrame as df

shape = (5000, 5)
Y = (np.sign(np.random.random(shape) - 0.5) + 1) / 2

# Labelsets stratification
see "On the Stratification of Multi-Label Data, Konstantinos Sechidis, Grigorios Tsoumakas, and Ioannis Vlahavas"

In [283]:
def LabelsetKFold(Y, n_folds = 3, random_state = None, shuffle = True, force = False):
    result = [None] * n_folds
    for i in range(n_folds):
        result[i] = [[],[]]
    sets = np.vstack({tuple(row) for row in Y})
    for s in sets:
        rows = np.where(np.all(Y == s, axis = 1))[0]
        n = len(rows)
        print n
        
        # Handling low objects per label count case
        n_folds_ = n_folds
        if force and n_folds > n:
            n_folds_ = n
        elif not force and n_folds > n:
            raise ValueError("LabelsetKFold: Force == False and n_folds = %d > %d = n. \
Set Force to True or reconsider your data. Labelset = %s" % (n_folds, n, str(s)))
            
        # Adding labels of size 1 to train
        # to each fold
        if force and n == 1:
            for i in range(n_folds):
                result[i][0].extend(rows)
            continue
        elif not force and n == 1:
            raise ValueError("LabelsetKFold: Force == False and n == 1. Set Force to True or reconsider your data. Labelset = %s" % (str(s)))
        
        folds = KFold(n_folds = n_folds_, n = n, random_state = random_state, shuffle = shuffle)
        
        i = 0
        while i < n_folds:
            for train, test in folds:
                result[i][0].extend(rows[train])
                result[i][1].extend(rows[test])
                i += 1
                if i >= n_folds:
                    break
    return result

In [320]:
fds = LabelsetKFold(Y, n_folds = 5, random_state = 1, force = False)

152
155
166
146
167
159
146
187
148
142
161
159
147
147
168
149
162
161
155
174
159
149
138
151
176
178
132
150
154
162
160
140


In [321]:
for train, test in fds:
    print len(train), len(test), len(train) + len(test)
    print train, test

3986 1014 5000
[42, 62, 70, 85, 111, 217, 299, 335, 353, 414, 465, 470, 481, 550, 690, 692, 711, 744, 769, 848, 866, 905, 910, 937, 948, 977, 1049, 1108, 1169, 1279, 1292, 1297, 1310, 1336, 1377, 1528, 1572, 1634, 1646, 1663, 1675, 1716, 1744, 1859, 1885, 1892, 1929, 2040, 2062, 2153, 2181, 2182, 2186, 2204, 2220, 2268, 2357, 2384, 2391, 2404, 2405, 2505, 2513, 2527, 2579, 2591, 2686, 2721, 2730, 2777, 2904, 3012, 3118, 3236, 3322, 3369, 3442, 3502, 3549, 3570, 3648, 3735, 3790, 3794, 3841, 3905, 3927, 3941, 3981, 3998, 4000, 4028, 4053, 4082, 4124, 4149, 4205, 4288, 4289, 4373, 4420, 4432, 4483, 4507, 4511, 4541, 4570, 4581, 4598, 4645, 4658, 4687, 4698, 4700, 4791, 4792, 4892, 4927, 4931, 4946, 4973, 13, 81, 137, 149, 174, 212, 278, 320, 325, 330, 349, 362, 395, 405, 558, 564, 594, 678, 735, 743, 760, 778, 808, 837, 859, 892, 934, 991, 1004, 1068, 1088, 1124, 1217, 1241, 1363, 1409, 1418, 1474, 1505, 1506, 1516, 1576, 1728, 1782, 1874, 1921, 1956, 1981, 2029, 2073, 2090, 2117, 2130, 

In [326]:
np.intersect1d(fds[0][1], fds[1][1])

array([], dtype=int64)

In [328]:
len(fds[1][0])

3993

# Iterative stratification
see "On the Stratification of Multi-Label Data, Konstantinos Sechidis, Grigorios Tsoumakas, and Ioannis Vlahavas"

In [416]:
def IterativeStratification(Y, k, r):
    D = Y.shape[0]
    L = Y.shape[1]
    c = np.array(r * D)
    
    Dset = [None] * L
    for i in range(L):
        Dset[i] = np.where(Y[:,i] == 1)[0]
    
    D_ = np.sum(Y[:] == 1, axis=0)
    print D_
    c_ = (np.array([c]).T.dot([D_])).T
    
    while D > 0:
        l = np.argmin(D_[np.where(D_ != 0)])
        D -= 1

In [417]:
k = 5
r = [1./ k] * k

In [418]:
IterativeStratification(Y, k, r)

[2487 2551 2514 2521 2467]


In [405]:
D_ = np.array([1,2,3,4,5,0])


0

In [343]:
np.array([0] * 4)

array([0, 0, 0, 0])

array([   0,    1,    2, ..., 4995, 4998, 4999])

In [ ]:
np.where(Y[:,0]==1)[0]